package ru.isands.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Employee service. Represents a row in the &quot;Employee_Employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.isands.model.impl.EmployeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.isands.model.impl.EmployeeImpl}.
 * </p>
 *
 * @author Joe Bloggs
 * @see Employee
 * @see ru.isands.model.impl.EmployeeImpl
 * @see ru.isands.model.impl.EmployeeModelImpl
 * @generated
 */
public interface EmployeeModel extends BaseModel<Employee> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a employee model instance should use the {@link Employee} interface instead.
     */

    /**
     * Returns the primary key of this employee.
     *
     * @return the primary key of this employee
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this employee.
     *
     * @param primaryKey the primary key of this employee
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the employee ID of this employee.
     *
     * @return the employee ID of this employee
     */
    public long getEmployeeId();

    /**
     * Sets the employee ID of this employee.
     *
     * @param employeeId the employee ID of this employee
     */
    public void setEmployeeId(long employeeId);

    /**
     * Returns the last name of this employee.
     *
     * @return the last name of this employee
     */
    @AutoEscape
    public String getLastName();

    /**
     * Sets the last name of this employee.
     *
     * @param lastName the last name of this employee
     */
    public void setLastName(String lastName);

    /**
     * Returns the first name of this employee.
     *
     * @return the first name of this employee
     */
    @AutoEscape
    public String getFirstName();

    /**
     * Sets the first name of this employee.
     *
     * @param firstName the first name of this employee
     */
    public void setFirstName(String firstName);

    /**
     * Returns the middle name of this employee.
     *
     * @return the middle name of this employee
     */
    @AutoEscape
    public String getMiddleName();

    /**
     * Sets the middle name of this employee.
     *
     * @param middleName the middle name of this employee
     */
    public void setMiddleName(String middleName);

    /**
     * Returns the sex of this employee.
     *
     * @return the sex of this employee
     */
    @AutoEscape
    public String getSex();

    /**
     * Sets the sex of this employee.
     *
     * @param sex the sex of this employee
     */
    public void setSex(String sex);

    /**
     * Returns the birthday date of this employee.
     *
     * @return the birthday date of this employee
     */
    public Date getBirthdayDate();

    /**
     * Sets the birthday date of this employee.
     *
     * @param birthdayDate the birthday date of this employee
     */
    public void setBirthdayDate(Date birthdayDate);

    /**
     * Returns the position ID of this employee.
     *
     * @return the position ID of this employee
     */
    public long getPositionId();

    /**
     * Sets the position ID of this employee.
     *
     * @param positionId the position ID of this employee
     */
    public void setPositionId(long positionId);

    /**
     * Returns the employment date of this employee.
     *
     * @return the employment date of this employee
     */
    public Date getEmploymentDate();

    /**
     * Sets the employment date of this employee.
     *
     * @param employmentDate the employment date of this employee
     */
    public void setEmploymentDate(Date employmentDate);

    /**
     * Returns the salary of this employee.
     *
     * @return the salary of this employee
     */
    @AutoEscape
    public String getSalary();

    /**
     * Sets the salary of this employee.
     *
     * @param salary the salary of this employee
     */
    public void setSalary(String salary);

    /**
     * Returns the work phone of this employee.
     *
     * @return the work phone of this employee
     */
    @AutoEscape
    public String getWorkPhone();

    /**
     * Sets the work phone of this employee.
     *
     * @param workPhone the work phone of this employee
     */
    public void setWorkPhone(String workPhone);

    /**
     * Returns the mobile phone of this employee.
     *
     * @return the mobile phone of this employee
     */
    @AutoEscape
    public String getMobilePhone();

    /**
     * Sets the mobile phone of this employee.
     *
     * @param mobilePhone the mobile phone of this employee
     */
    public void setMobilePhone(String mobilePhone);

    /**
     * Returns the bank ID of this employee.
     *
     * @return the bank ID of this employee
     */
    public long getBankId();

    /**
     * Sets the bank ID of this employee.
     *
     * @param bankId the bank ID of this employee
     */
    public void setBankId(long bankId);

    /**
     * Returns the is archived of this employee.
     *
     * @return the is archived of this employee
     */
    public Boolean getIsArchived();

    /**
     * Sets the is archived of this employee.
     *
     * @param isArchived the is archived of this employee
     */
    public void setIsArchived(Boolean isArchived);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Employee employee);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Employee> toCacheModel();

    @Override
    public Employee toEscapedModel();

    @Override
    public Employee toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
