package ru.isands.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import ru.isands.model.Bank;

import ru.isands.service.BankLocalServiceUtil;

/**
 * The extended model base implementation for the Bank service. Represents a row in the &quot;Employee_Bank&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BankImpl}.
 * </p>
 *
 * @author Joe Bloggs
 * @see BankImpl
 * @see ru.isands.model.Bank
 * @generated
 */
public abstract class BankBaseImpl extends BankModelImpl implements Bank {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a bank model instance should use the {@link Bank} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            BankLocalServiceUtil.addBank(this);
        } else {
            BankLocalServiceUtil.updateBank(this);
        }
    }
}
